const VALID_DURATIONS = [30, 45, 60, 90, 120];
const TIME_RE = /^\d{2}:\d{2}$/;
const MAX_CLASSES_PER_ISSUER = 20;
const MAX_TOPICS_PER_CLASS = 10;
const MAX_CLASS_NAME_LENGTH = 255;
const MAX_CLASS_DESC_LENGTH = 1000;
const MAX_MESSAGE_LENGTH = 500;

module.exports = {
  VALID_DURATIONS,
  TIME_RE,
  MAX_CLASSES_PER_ISSUER,
  MAX_TOPICS_PER_CLASS,
  MAX_CLASS_NAME_LENGTH,
  MAX_CLASS_DESC_LENGTH,
  MAX_MESSAGE_LENGTH,
};
