import React from 'react';
import LegalLayout from '@/components/LegalLayout';
import { useTranslation } from 'react-i18next';

const TermsOfService = () => {
  const { i18n } = useTranslation();
  const isEs = i18n.language.startsWith('es');

  return (
    <LegalLayout title={isEs ? "Términos de Servicio - Hackchain" : "Terms of Service - Hackchain"} lastUpdated={isEs ? "15 Abril 2026" : "April 15, 2026"}>
      {isEs ? (
        <>
      <h2>1. Objeto</h2>
      <p>
        Hackchain proporciona una infraestructura web3 avanzada que permite a instituciones, talentos y empresas interactuar bajo un marco de confianza descentralizada. Nuestra plataforma permite:
      </p>
      <ul>
        <li>La emisión segura de certificados (Non-Fungible Tokens o NFTs).</li>
        <li>La validación inmutable de habilidades y trayectorias profesionales.</li>
      </ul>

      <h2>2. Uso de la plataforma</h2>
      <p>Al acceder y utilizar los servicios de Hackchain, el usuario se compromete estrictamente a:</p>
      <ul>
        <li>Proporcionar información personal, académica y profesional completamente veraz.</li>
        <li>No utilizar la plataforma ni sus contratos inteligentes de forma ilegal, fraudulenta o maliciosa.</li>
      </ul>

      <h2>3. Propiedad intelectual</h2>
      <p>
        Todo el código fuente, diseño, interfaces, marcas registradas y propiedad intelectual generada para el funcionamiento de la plataforma pertenecen de forma exclusiva a Hackchain, <strong>salvo</strong> el contenido y la metadata directamente generada por los usuarios e incrustada en sus propios certificados o perfiles, que les pertenece a ellos bajo los términos de Web3.
      </p>

      <h2>4. Reglas Críticas Blockchain</h2>
      <p>El uso del protocolo Hackchain conlleva aceptar las siguientes reglas tecnológicas fundamentales:</p>
      <ul>
        <li>Los registros incrustados en Blockchain son <strong>permanentes</strong> y trazables de por vida.</li>
        <li>Una vez firmados, los registros no pueden modificarse ni eliminarse bajo ninguna exigencia convencional de borrado.</li>
      </ul>

      <h2>5. LIMITACIÓN DE RESPONSABILIDAD</h2>
      <div className="bg-red-900/10 border border-red-500/50 p-6 rounded-xl my-6">
        <p className="font-bold text-red-400 mb-4 mt-0 text-lg uppercase tracking-wider">Aviso Legal Importante</p>
        <p className="m-0 text-gray-300">Hackchain y sus desarrolladores o afiliados no serán legalmente responsables bajo ninguna circunstancia por:</p>
        <ul className="mt-4 mb-0 text-sm text-gray-400">
          <li>Pérdida de acceso o claves privadas (Seed Phrases) de Wallets de usuarios.</li>
          <li>Errores tipográficos, humanos o lógicos ejecutados por el usuario durante la firma de transacciones.</li>
          <li>Fallas críticas de redes blockchain de terceros (Ethereum, Polygon, o Layer 2s subyacentes).</li>
          <li>La libre interpretación, validez en el mundo real, o utilidad que terceros brinden a las certificaciones acuñadas en el protocolo.</li>
        </ul>
      </div>

      <h2>6. Jurisdicción</h2>
      <p>
        Cualquier controversia relacionada con el uso de la plataforma estará sujeta a la jurisdicción exclusiva y a las leyes federales de <strong>México</strong>.
      </p>
      </>
      ) : (
      <>
      <h2>1. Object</h2>
      <p>
        Hackchain provides advanced web3 infrastructure allowing institutions, talent, and companies to interact under a decentralized trust framework. Our platform enables:
      </p>
      <ul>
        <li>Secure issuance of certificates (Non-Fungible Tokens or NFTs).</li>
        <li>Immutable validation of professional skills and career trajectories.</li>
      </ul>

      <h2>2. Platform Usage</h2>
      <p>By accessing and using Hackchain services, the user strictly commits to:</p>
      <ul>
        <li>Provide completely truthful personal, academic, and professional information.</li>
        <li>Not use the platform or its smart contracts illegally, fraudulently, or maliciously.</li>
      </ul>

      <h2>3. Intellectual Property</h2>
      <p>
        All source code, design, interfaces, trademarks, and intellectual property generated for platform operations belong exclusively to Hackchain, <strong>except</strong> for content and metadata directly generated by users embedded in their own certificates or profiles, which belongs to them under Web3 terms.
      </p>

      <h2>4. Critical Blockchain Rules</h2>
      <p>Using the Hackchain protocol entails accepting the following fundamental technological rules:</p>
      <ul>
        <li>Records embedded in the Blockchain are <strong>permanent</strong> and traceable for life.</li>
        <li>Once signed, records cannot be modified or deleted under any conventional deletion requests.</li>
      </ul>

      <h2>5. LIMITATION OF LIABILITY</h2>
      <div className="bg-red-900/10 border border-red-500/50 p-6 rounded-xl my-6">
        <p className="font-bold text-red-400 mb-4 mt-0 text-lg uppercase tracking-wider">Important Legal Notice</p>
        <p className="m-0 text-gray-300">Hackchain and its developers or affiliates shall not be legally liable under any circumstances for:</p>
        <ul className="mt-4 mb-0 text-sm text-gray-400">
          <li>Loss of access or private keys (Seed Phrases) belonging to user Wallets.</li>
          <li>Typographical, human, or logical errors executed by the user while signing transactions.</li>
          <li>Critical failures of third-party blockchain networks (Ethereum, Polygon, or underlying Layer 2s).</li>
          <li>The free interpretation, real-world validity, or utility that third parties grant to certifications minted in the protocol.</li>
        </ul>
      </div>

      <h2>6. Jurisdiction</h2>
      <p>
        Any controversy related to the use of the platform shall be subject to the exclusive jurisdiction and federal laws of <strong>Mexico</strong>.
      </p>
      </>
      )}
    </LegalLayout>
  );
};

export default TermsOfService;
